name: taptask
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      # Set up NodeJS version 20
      - name: Setup NodeJS version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4
      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
      # Set un Java environment
      - name: Set up Java environment
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      # Lint check
      - name: Lint check
        run: |
          npm run lint:fix && npm run format:check
      # Run unit test
      - name: Running unit tests
        run: |
          npm run test
      # Build Android apk for release
      - uses: actions/checkout@v4
      - name: Clean gradle project
        run: |
          cd android && ./gradlew clean
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
