name: taptask
on:
  push:
    branches:
      - master
jobs:
  install-project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          npm install
  lint-check:
    needs: install-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          npm install
      - name: Check Prettier formatting
        run: |
          npm run lint:fix && npm run format:check
  unit-tests:
    needs: lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: |
          npm install
      - name: Running unit tests
        run: |
          npm run test
  build-android:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
